version: '3'
services:
  spark-master:
    image: jlaura/spark-master
    networks:
      - workbench
    volumes:
      - /work/projects/jaxa02/SP_Level2C/:/kaguya
    ports:
      - "50082:8080"
      - "50077:7077"
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8080
      placement:
        constraints: [node.role == manager]
    env_file:
      - ./hadoop.env

  spark-worker:
    image: jlaura/spark-worker
    networks:
      - workbench
    volumes:
      - /work/projects/jaxa02/SP_Level2C/:/kaguya
    environment:
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=8G
    deploy:
      mode: replicated
      replicas: 6
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8081
      placement:
        constraints: [node.role == worker]
    env_file:
      - ./hadoop.env
    depends_on: 
      # This does not guarantee that the service is ready, just started
      - spark-master

networks:
  workbench:
    external: true
