version: '3'
services:

  jupyter:
    image: jlaura/spark-jupyter
    ports: 
      - "50089:8888"
    pid: "host"
    environment:
      TINI_SUBREAPER: "true"
      NB_UID: 2291
      NB_GID: 1800
    volumes:
      - /scratch/jlaura/kaguya_stacks/notebooks/:/home/jovyan/work
      - /work/projects/jaxa02/SP_Level2C/:/kaguya
      - /scratch/jlaura/kaguya_stacks/jars/:/jars
    networks: 
      - workbench  
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8888

networks:
  workbench:
    external: true
